/** Single source of truth for API paths — used by the client and the MSW handlers. */
export const API_BASE = '/api';

export const ROUTES = {
  // auth
  otpRequest: `${API_BASE}/auth/otp/request`,
  otpVerify: `${API_BASE}/auth/otp/verify`,
  register: `${API_BASE}/auth/register`,
  adminUsers: `${API_BASE}/admin/auth/users`,
  adminLogin: `${API_BASE}/admin/auth/login`,
  // member
  me: `${API_BASE}/me`,
  wallet: `${API_BASE}/me/wallet`,
  topUp: `${API_BASE}/me/topup`,
  myQr: `${API_BASE}/me/qr`,
  myBookings: `${API_BASE}/me/bookings`,
  myVisits: `${API_BASE}/me/visits`,
  myNotifications: `${API_BASE}/me/notifications`,
  readNotifications: `${API_BASE}/me/notifications/read-all`,
  // shared catalog
  branches: `${API_BASE}/branches`,
  packages: `${API_BASE}/packages`,
  validateVoucher: `${API_BASE}/vouchers/validate`,
  sessions: `${API_BASE}/sessions`,
  session: (id: string) => `${API_BASE}/sessions/${id}`,
  bookSession: (id: string) => `${API_BASE}/sessions/${id}/book`,
  cancelBooking: (id: string) => `${API_BASE}/bookings/${id}/cancel`,
  simulatePayment: (id: string) => `${API_BASE}/payments/${id}/simulate`,
  gateScan: (gateId: string) => `${API_BASE}/gates/${gateId}/scan`,
  // admin
  adminMembers: `${API_BASE}/admin/members`,
  adminMember: (id: string) => `${API_BASE}/admin/members/${id}`,
  adminAdjust: (id: string) => `${API_BASE}/admin/members/${id}/adjust`,
  adminReverseEntry: (entryId: string) => `${API_BASE}/admin/ledger/${entryId}/reverse`,
  adminClassTypes: `${API_BASE}/admin/class-types`,
  adminClassType: (id: string) => `${API_BASE}/admin/class-types/${id}`,
  adminSessions: `${API_BASE}/admin/sessions`,
  adminSession: (id: string) => `${API_BASE}/admin/sessions/${id}`,
  adminSessionAction: (id: string, action: 'publish' | 'cancel' | 'complete') =>
    `${API_BASE}/admin/sessions/${id}/${action}`,
  adminBook: `${API_BASE}/admin/bookings`,
  adminNoShow: (bookingId: string) => `${API_BASE}/admin/bookings/${bookingId}/no-show`,
  adminCheckIn: (bookingId: string) => `${API_BASE}/admin/bookings/${bookingId}/check-in`,
  adminCoaches: `${API_BASE}/admin/coaches`,
  adminCoach: (id: string) => `${API_BASE}/admin/coaches/${id}`,
  adminGates: `${API_BASE}/admin/gates`,
  adminAccessLogs: `${API_BASE}/admin/access-logs`,
  adminPackages: `${API_BASE}/admin/packages`,
  adminPackage: (id: string) => `${API_BASE}/admin/packages/${id}`,
  adminPayments: `${API_BASE}/admin/payments`,
  adminRefund: (id: string) => `${API_BASE}/admin/payments/${id}/refund`,
  adminVouchers: `${API_BASE}/admin/vouchers`,
  adminVoucher: (id: string) => `${API_BASE}/admin/vouchers/${id}`,
  adminVoucherStatus: (id: string) => `${API_BASE}/admin/vouchers/${id}/status`,
  adminCampaigns: `${API_BASE}/admin/campaigns`,
  adminCampaignSend: (id: string) => `${API_BASE}/admin/campaigns/${id}/send`,
  adminDashboard: `${API_BASE}/admin/reports/dashboard`,
  adminReportSales: `${API_BASE}/admin/reports/sales`,
  adminReportVisits: `${API_BASE}/admin/reports/visits`,
  adminReportCredits: `${API_BASE}/admin/reports/credits`,
  adminAudit: `${API_BASE}/admin/audit`,
  adminBranches: `${API_BASE}/admin/branches`,
  adminBranch: (id: string) => `${API_BASE}/admin/branches/${id}`,
  adminRules: `${API_BASE}/admin/rules`,
  // devtools
  devReset: `${API_BASE}/dev/reset`,
  devExpirySweep: `${API_BASE}/dev/expiry-sweep`,
} as const;
